// Code generated by sqlc. DO NOT EDIT.

package dbq

import (
	"database/sql"
)

type Deletion struct {
	ID          int64
	ObjectKey   string
	MultipartID sql.NullString
	NotBefore   int64
}

type Pack struct {
	ID            int64
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
	Sketch        []byte
}

type Ref struct {
	Name      string
	PackID    int64
	UpdatedBy string
	UpdatedAt int64
}

type SketchKey struct {
	Key    []byte
	PackID int64
}

type Upload struct {
	ID          string
	Name        string
	Root        []byte
	ParentID    sql.NullInt64
	Uploader    string
	DataKey     string
	IndexKey    string
	LinksKey    string
	MultipartID sql.NullString
	DataSize    int64
	Objects     int64
	State       string
	IssuedAt    int64
	Deadline    int64
}
