// Code generated by sqlc. DO NOT EDIT.
// source: packs.sql

package dbq

import (
	"context"
	"database/sql"
	"strings"
)

const childRoots = `-- name: ChildRoots :many
SELECT root FROM packs WHERE parent_id = ?1 ORDER BY root
`

func (q *Queries) ChildRoots(ctx context.Context, parentID sql.NullInt64) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, childRoots, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var root []byte
		if err := rows.Scan(&root); err != nil {
			return nil, err
		}
		items = append(items, root)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePackIfDead = `-- name: DeletePackIfDead :many
DELETE FROM packs
WHERE packs.id = ?1
  AND NOT EXISTS (SELECT 1 FROM refs AS r WHERE r.pack_id = packs.id)
  AND NOT EXISTS (SELECT 1 FROM packs AS c WHERE c.parent_id = packs.id)
  AND NOT EXISTS (SELECT 1 FROM uploads AS u WHERE u.parent_id = packs.id)
RETURNING parent_id, data_key, index_key, links_key
`

type DeletePackIfDeadRow struct {
	ParentID sql.NullInt64
	DataKey  string
	IndexKey string
	LinksKey sql.NullString
}

// The pack with the given ID, if nothing holds it: no row otherwise. A patch
// pack that goes can leave its base without a holder, so the parent comes
// back to be looked at next.
func (q *Queries) DeletePackIfDead(ctx context.Context, id int64) ([]DeletePackIfDeadRow, error) {
	rows, err := q.db.QueryContext(ctx, deletePackIfDead, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeletePackIfDeadRow{}
	for rows.Next() {
		var i DeletePackIfDeadRow
		if err := rows.Scan(
			&i.ParentID,
			&i.DataKey,
			&i.IndexKey,
			&i.LinksKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPack = `-- name: InsertPack :one

INSERT INTO packs (
    root, parent_id, data_key, index_key, links_key, data_size, index_size,
    links_size, objects, bytes, shared_objects, shared_bytes, uploader,
    uploaded_at, sketch, unpacked
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8, ?9,
    ?10, ?11, ?12,
    ?13, ?14, ?15,
    ?16
)
RETURNING id
`

type InsertPackParams struct {
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
	Sketch        []byte
	Unpacked      int64
}

// The reads of a pack leave its sketch out: it is some kilobytes, and only
// the nearest search wants it.
func (q *Queries) InsertPack(ctx context.Context, arg InsertPackParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPack,
		arg.Root,
		arg.ParentID,
		arg.DataKey,
		arg.IndexKey,
		arg.LinksKey,
		arg.DataSize,
		arg.IndexSize,
		arg.LinksSize,
		arg.Objects,
		arg.Bytes,
		arg.SharedObjects,
		arg.SharedBytes,
		arg.Uploader,
		arg.UploadedAt,
		arg.Sketch,
		arg.Unpacked,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSketchKey = `-- name: InsertSketchKey :exec
INSERT INTO sketch_keys (key, pack_id)
VALUES (?1, ?2)
`

type InsertSketchKeyParams struct {
	Key    []byte
	PackID int64
}

func (q *Queries) InsertSketchKey(ctx context.Context, arg InsertSketchKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertSketchKey, arg.Key, arg.PackID)
	return err
}

const listPacks = `-- name: ListPacks :many
SELECT p.id, p.root, p.parent_id, p.data_key, p.index_key, p.links_key,
       p.data_size, p.index_size, p.links_size, p.objects, p.bytes,
       p.shared_objects, p.shared_bytes, p.uploader, p.uploaded_at,
       parent.root AS parent_root,
       (SELECT count(*) FROM refs AS r WHERE r.pack_id = p.id) AS refs,
       (SELECT count(*) FROM packs AS c WHERE c.parent_id = p.id) AS children
FROM packs AS p
LEFT JOIN packs AS parent ON parent.id = p.parent_id
WHERE p.id > ?1
ORDER BY p.id
LIMIT ?2
`

type ListPacksParams struct {
	AfterID int64
	N       int64
}

type ListPacksRow struct {
	ID            int64
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
	ParentRoot    []byte
	Refs          int64
	Children      int64
}

func (q *Queries) ListPacks(ctx context.Context, arg ListPacksParams) ([]ListPacksRow, error) {
	rows, err := q.db.QueryContext(ctx, listPacks, arg.AfterID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPacksRow{}
	for rows.Next() {
		var i ListPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Root,
			&i.ParentID,
			&i.DataKey,
			&i.IndexKey,
			&i.LinksKey,
			&i.DataSize,
			&i.IndexSize,
			&i.LinksSize,
			&i.Objects,
			&i.Bytes,
			&i.SharedObjects,
			&i.SharedBytes,
			&i.Uploader,
			&i.UploadedAt,
			&i.ParentRoot,
			&i.Refs,
			&i.Children,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packByID = `-- name: PackByID :one
SELECT id, root, parent_id, data_key, index_key, links_key, data_size,
       index_size, links_size, objects, bytes, shared_objects, shared_bytes,
       uploader, uploaded_at
FROM packs
WHERE id = ?1
`

type PackByIDRow struct {
	ID            int64
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
}

func (q *Queries) PackByID(ctx context.Context, id int64) (PackByIDRow, error) {
	row := q.db.QueryRowContext(ctx, packByID, id)
	var i PackByIDRow
	err := row.Scan(
		&i.ID,
		&i.Root,
		&i.ParentID,
		&i.DataKey,
		&i.IndexKey,
		&i.LinksKey,
		&i.DataSize,
		&i.IndexSize,
		&i.LinksSize,
		&i.Objects,
		&i.Bytes,
		&i.SharedObjects,
		&i.SharedBytes,
		&i.Uploader,
		&i.UploadedAt,
	)
	return i, err
}

const packByRoot = `-- name: PackByRoot :one
SELECT id, root, parent_id, data_key, index_key, links_key, data_size,
       index_size, links_size, objects, bytes, shared_objects, shared_bytes,
       uploader, uploaded_at
FROM packs
WHERE root = ?1
`

type PackByRootRow struct {
	ID            int64
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
}

func (q *Queries) PackByRoot(ctx context.Context, root []byte) (PackByRootRow, error) {
	row := q.db.QueryRowContext(ctx, packByRoot, root)
	var i PackByRootRow
	err := row.Scan(
		&i.ID,
		&i.Root,
		&i.ParentID,
		&i.DataKey,
		&i.IndexKey,
		&i.LinksKey,
		&i.DataSize,
		&i.IndexSize,
		&i.LinksSize,
		&i.Objects,
		&i.Bytes,
		&i.SharedObjects,
		&i.SharedBytes,
		&i.Uploader,
		&i.UploadedAt,
	)
	return i, err
}

const sharingPacks = `-- name: SharingPacks :many
SELECT p.id, p.root, p.sketch, count(*) AS shared
FROM sketch_keys AS s
JOIN packs AS p ON p.id = s.pack_id
WHERE s.key IN (/*SLICE:keys*/?)
GROUP BY p.id
ORDER BY count(*) DESC, p.root ASC
LIMIT 16
`

type SharingPacksRow struct {
	ID     int64
	Root   []byte
	Sketch []byte
	Shared int64
}

// The 16 packs that share the most of the given keys with their sketches,
// and how many each shares. Blobs compare as their bytes, so the lower root
// wins a tie. The limit is written out: sqlc numbers its parameters, and a
// numbered one after the list of keys would be bound to one of the keys.
func (q *Queries) SharingPacks(ctx context.Context, keys [][]byte) ([]SharingPacksRow, error) {
	query := sharingPacks
	var queryParams []interface{}
	if len(keys) > 0 {
		for _, v := range keys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:keys*/?", strings.Repeat(",?", len(keys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:keys*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SharingPacksRow{}
	for rows.Next() {
		var i SharingPacksRow
		if err := rows.Scan(
			&i.ID,
			&i.Root,
			&i.Sketch,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPacksByChildren = `-- name: TopPacksByChildren :many
SELECT p.id, p.root, p.parent_id, p.data_key, p.index_key, p.links_key,
       p.data_size, p.index_size, p.links_size, p.objects, p.bytes,
       p.shared_objects, p.shared_bytes, p.uploader, p.uploaded_at,
       (SELECT count(*) FROM refs AS r WHERE r.pack_id = p.id) AS refs,
       count(*) AS children,
       CAST(max(c.shared_bytes) AS INTEGER) AS largest_share
FROM packs AS c
JOIN packs AS p ON p.id = c.parent_id
GROUP BY p.id
ORDER BY count(*) DESC, p.id
LIMIT ?1
`

type TopPacksByChildrenRow struct {
	ID            int64
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
	Refs          int64
	Children      int64
	LargestShare  int64
}

// The packs the most patch packs lean on, the most first and among equals
// the older. Only a base pack is leaned on, so none of them has a parent.
func (q *Queries) TopPacksByChildren(ctx context.Context, n int64) ([]TopPacksByChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, topPacksByChildren, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPacksByChildrenRow{}
	for rows.Next() {
		var i TopPacksByChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Root,
			&i.ParentID,
			&i.DataKey,
			&i.IndexKey,
			&i.LinksKey,
			&i.DataSize,
			&i.IndexSize,
			&i.LinksSize,
			&i.Objects,
			&i.Bytes,
			&i.SharedObjects,
			&i.SharedBytes,
			&i.Uploader,
			&i.UploadedAt,
			&i.Refs,
			&i.Children,
			&i.LargestShare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPacksByRefs = `-- name: TopPacksByRefs :many
SELECT p.id, p.root, p.parent_id, p.data_key, p.index_key, p.links_key,
       p.data_size, p.index_size, p.links_size, p.objects, p.bytes,
       p.shared_objects, p.shared_bytes, p.uploader, p.uploaded_at,
       parent.root AS parent_root,
       count(*) AS refs,
       (SELECT count(*) FROM packs AS c WHERE c.parent_id = p.id) AS children,
       CAST((SELECT COALESCE(max(c.shared_bytes), 0) FROM packs AS c WHERE c.parent_id = p.id) AS INTEGER) AS largest_share
FROM refs AS r
JOIN packs AS p ON p.id = r.pack_id
LEFT JOIN packs AS parent ON parent.id = p.parent_id
GROUP BY p.id
ORDER BY count(*) DESC, p.id
LIMIT ?1
`

type TopPacksByRefsRow struct {
	ID            int64
	Root          []byte
	ParentID      sql.NullInt64
	DataKey       string
	IndexKey      string
	LinksKey      sql.NullString
	DataSize      int64
	IndexSize     int64
	LinksSize     int64
	Objects       int64
	Bytes         int64
	SharedObjects int64
	SharedBytes   int64
	Uploader      string
	UploadedAt    int64
	ParentRoot    []byte
	Refs          int64
	Children      int64
	LargestShare  int64
}

// The packs the most refs point at, the most first and among equals the
// older. largest_share is the most of a pack's bytes that one of the patch
// packs leaning on it uses, 0 when none leans on it.
func (q *Queries) TopPacksByRefs(ctx context.Context, n int64) ([]TopPacksByRefsRow, error) {
	rows, err := q.db.QueryContext(ctx, topPacksByRefs, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPacksByRefsRow{}
	for rows.Next() {
		var i TopPacksByRefsRow
		if err := rows.Scan(
			&i.ID,
			&i.Root,
			&i.ParentID,
			&i.DataKey,
			&i.IndexKey,
			&i.LinksKey,
			&i.DataSize,
			&i.IndexSize,
			&i.LinksSize,
			&i.Objects,
			&i.Bytes,
			&i.SharedObjects,
			&i.SharedBytes,
			&i.Uploader,
			&i.UploadedAt,
			&i.ParentRoot,
			&i.Refs,
			&i.Children,
			&i.LargestShare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
