// Code generated by sqlc. DO NOT EDIT.
// source: refs.sql

package dbq

import (
	"context"
)

const deleteRef = `-- name: DeleteRef :execrows
DELETE FROM refs WHERE name = ?1
`

func (q *Queries) DeleteRef(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRef, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listRefsBetween = `-- name: ListRefsBetween :many
SELECT r.name, r.pack_id, r.updated_by, r.updated_at, p.root
FROM refs AS r
JOIN packs AS p ON p.id = r.pack_id
WHERE r.name >= ?1 AND r.name > ?2
  AND r.name < ?3
ORDER BY r.name
LIMIT ?4
`

type ListRefsBetweenParams struct {
	Lower string
	After string
	Upper string
	N     int64
}

type ListRefsBetweenRow struct {
	Name      string
	PackID    int64
	UpdatedBy string
	UpdatedAt int64
	Root      []byte
}

func (q *Queries) ListRefsBetween(ctx context.Context, arg ListRefsBetweenParams) ([]ListRefsBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, listRefsBetween,
		arg.Lower,
		arg.After,
		arg.Upper,
		arg.N,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefsBetweenRow{}
	for rows.Next() {
		var i ListRefsBetweenRow
		if err := rows.Scan(
			&i.Name,
			&i.PackID,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Root,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefsFrom = `-- name: ListRefsFrom :many
SELECT r.name, r.pack_id, r.updated_by, r.updated_at, p.root
FROM refs AS r
JOIN packs AS p ON p.id = r.pack_id
WHERE r.name >= ?1 AND r.name > ?2
ORDER BY r.name
LIMIT ?3
`

type ListRefsFromParams struct {
	Lower string
	After string
	N     int64
}

type ListRefsFromRow struct {
	Name      string
	PackID    int64
	UpdatedBy string
	UpdatedAt int64
	Root      []byte
}

// The names from lower on that come after the given one. A prefix is listed
// as a range of names, never with LIKE: its characters are literal.
func (q *Queries) ListRefsFrom(ctx context.Context, arg ListRefsFromParams) ([]ListRefsFromRow, error) {
	rows, err := q.db.QueryContext(ctx, listRefsFrom, arg.Lower, arg.After, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefsFromRow{}
	for rows.Next() {
		var i ListRefsFromRow
		if err := rows.Scan(
			&i.Name,
			&i.PackID,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.Root,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refByName = `-- name: RefByName :one
SELECT r.name, r.pack_id, r.updated_by, r.updated_at, p.root
FROM refs AS r
JOIN packs AS p ON p.id = r.pack_id
WHERE r.name = ?1
`

type RefByNameRow struct {
	Name      string
	PackID    int64
	UpdatedBy string
	UpdatedAt int64
	Root      []byte
}

func (q *Queries) RefByName(ctx context.Context, name string) (RefByNameRow, error) {
	row := q.db.QueryRowContext(ctx, refByName, name)
	var i RefByNameRow
	err := row.Scan(
		&i.Name,
		&i.PackID,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Root,
	)
	return i, err
}

const refNamesOfPack = `-- name: RefNamesOfPack :many
SELECT name FROM refs WHERE pack_id = ?1 ORDER BY name
`

func (q *Queries) RefNamesOfPack(ctx context.Context, packID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, refNamesOfPack, packID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRef = `-- name: UpsertRef :exec
INSERT INTO refs (name, pack_id, updated_by, updated_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (name) DO UPDATE SET
    pack_id = excluded.pack_id,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at
`

type UpsertRefParams struct {
	Name      string
	PackID    int64
	UpdatedBy string
	UpdatedAt int64
}

func (q *Queries) UpsertRef(ctx context.Context, arg UpsertRefParams) error {
	_, err := q.db.ExecContext(ctx, upsertRef,
		arg.Name,
		arg.PackID,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
