// Code generated by sqlc. DO NOT EDIT.
// source: stats.sql

package dbq

import (
	"context"
)

const countDeletions = `-- name: CountDeletions :one
SELECT count(*) FROM deletions
`

func (q *Queries) CountDeletions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeletions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRefs = `-- name: CountRefs :one
SELECT count(*) FROM refs
`

func (q *Queries) CountRefs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRefs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUploads = `-- name: CountUploads :one
SELECT count(*) FROM uploads
`

func (q *Queries) CountUploads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUploads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const packTotals = `-- name: PackTotals :one
SELECT count(parent_id) AS patch_packs,
       count(*) - count(parent_id) AS base_packs,
       CAST(COALESCE(sum(bytes), 0) AS INTEGER) AS pack_bytes,
       CAST(COALESCE(sum(data_size), 0) AS INTEGER) AS data_bytes,
       CAST(COALESCE(sum(index_size + links_size), 0) AS INTEGER) AS index_bytes,
       CAST(COALESCE(sum(1 - verified), 0) AS INTEGER) AS unverified_packs
FROM packs
`

type PackTotalsRow struct {
	PatchPacks      int64
	BasePacks       int64
	PackBytes       int64
	DataBytes       int64
	IndexBytes      int64
	UnverifiedPacks int64
}

// Every pack once: how many of each kind there are, what their objects come
// to as they are, what the bucket holds of them, and how many of them were
// recorded without being verified.
func (q *Queries) PackTotals(ctx context.Context) (PackTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, packTotals)
	var i PackTotalsRow
	err := row.Scan(
		&i.PatchPacks,
		&i.BasePacks,
		&i.PackBytes,
		&i.DataBytes,
		&i.IndexBytes,
		&i.UnverifiedPacks,
	)
	return i, err
}

const refTotals = `-- name: RefTotals :one
SELECT CAST(COALESCE(sum(p.unpacked), 0) AS INTEGER) AS unpacked_bytes,
       CAST(COALESCE(sum(p.bytes + p.shared_bytes), 0) AS INTEGER) AS object_bytes
FROM refs AS r
JOIN packs AS p ON p.id = r.pack_id
`

type RefTotalsRow struct {
	UnpackedBytes int64
	ObjectBytes   int64
}

// Over refs, not packs: two refs on one pack count it twice, as two
// directories would hold its content twice.
func (q *Queries) RefTotals(ctx context.Context) (RefTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, refTotals)
	var i RefTotalsRow
	err := row.Scan(&i.UnpackedBytes, &i.ObjectBytes)
	return i, err
}

const unreferencedTotals = `-- name: UnreferencedTotals :one
SELECT count(*) AS packs,
       CAST(COALESCE(sum(p.bytes), 0) AS INTEGER) AS pack_bytes,
       CAST(COALESCE(sum(p.data_size), 0) AS INTEGER) AS data_bytes
FROM packs AS p
WHERE NOT EXISTS (SELECT 1 FROM refs AS r WHERE r.pack_id = p.id)
`

type UnreferencedTotalsRow struct {
	Packs     int64
	PackBytes int64
	DataBytes int64
}

// The packs no ref points at. A pack without a ref is there because
// something leans on it: patch packs, or an upload that is to become one.
func (q *Queries) UnreferencedTotals(ctx context.Context) (UnreferencedTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, unreferencedTotals)
	var i UnreferencedTotalsRow
	err := row.Scan(&i.Packs, &i.PackBytes, &i.DataBytes)
	return i, err
}
