// Code generated by sqlc. DO NOT EDIT.
// source: stats.sql

package dbq

import (
	"context"
)

const countDeletions = `-- name: CountDeletions :one
SELECT count(*) FROM deletions
`

func (q *Queries) CountDeletions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeletions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRefs = `-- name: CountRefs :one
SELECT count(*) FROM refs
`

func (q *Queries) CountRefs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRefs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUploads = `-- name: CountUploads :one
SELECT count(*) FROM uploads
`

func (q *Queries) CountUploads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUploads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const logicalBytes = `-- name: LogicalBytes :one
SELECT CAST(COALESCE(sum(p.bytes + p.shared_bytes), 0) AS INTEGER)
FROM refs AS r
JOIN packs AS p ON p.id = r.pack_id
`

// Over refs, not packs: two refs on one pack count it twice.
func (q *Queries) LogicalBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, logicalBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const packTotals = `-- name: PackTotals :one
SELECT count(parent_id) AS patch_packs,
       count(*) - count(parent_id) AS base_packs,
       CAST(COALESCE(sum(data_size + index_size + links_size), 0) AS INTEGER) AS s3_bytes,
       CAST(COALESCE(sum(data_size), 0) AS INTEGER) AS data_bytes,
       CAST(COALESCE(sum(bytes), 0) AS INTEGER) AS stored_bytes
FROM packs
`

type PackTotalsRow struct {
	PatchPacks  int64
	BasePacks   int64
	S3Bytes     int64
	DataBytes   int64
	StoredBytes int64
}

func (q *Queries) PackTotals(ctx context.Context) (PackTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, packTotals)
	var i PackTotalsRow
	err := row.Scan(
		&i.PatchPacks,
		&i.BasePacks,
		&i.S3Bytes,
		&i.DataBytes,
		&i.StoredBytes,
	)
	return i, err
}
