// Code generated by sqlc. DO NOT EDIT.
// source: uploads.sql

package dbq

import (
	"context"
	"database/sql"
)

const deleteDeletion = `-- name: DeleteDeletion :exec
DELETE FROM deletions WHERE id = ?1
`

func (q *Queries) DeleteDeletion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDeletion, id)
	return err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE id = ?1
`

func (q *Queries) DeleteUpload(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUpload, id)
	return err
}

const dueDeletions = `-- name: DueDeletions :many
SELECT id, object_key, multipart_id
FROM deletions
WHERE not_before <= ?1
ORDER BY id
LIMIT ?2
`

type DueDeletionsParams struct {
	Now int64
	N   int64
}

type DueDeletionsRow struct {
	ID          int64
	ObjectKey   string
	MultipartID sql.NullString
}

// In the order they were queued, so the abort of a multipart upload comes
// before the delete of the object it may have completed.
func (q *Queries) DueDeletions(ctx context.Context, arg DueDeletionsParams) ([]DueDeletionsRow, error) {
	rows, err := q.db.QueryContext(ctx, dueDeletions, arg.Now, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueDeletionsRow{}
	for rows.Next() {
		var i DueDeletionsRow
		if err := rows.Scan(&i.ID, &i.ObjectKey, &i.MultipartID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredUploads = `-- name: ExpiredUploads :many
SELECT id, name, root, parent_id, uploader, data_key, index_key, links_key, multipart_id, data_size, objects, state, issued_at, deadline FROM uploads
WHERE state = 'pending' AND deadline < ?1
ORDER BY id
`

// An upload being verified is not expired under its verifier.
func (q *Queries) ExpiredUploads(ctx context.Context, now int64) ([]Upload, error) {
	rows, err := q.db.QueryContext(ctx, expiredUploads, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Root,
			&i.ParentID,
			&i.Uploader,
			&i.DataKey,
			&i.IndexKey,
			&i.LinksKey,
			&i.MultipartID,
			&i.DataSize,
			&i.Objects,
			&i.State,
			&i.IssuedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDeletion = `-- name: InsertDeletion :exec
INSERT INTO deletions (object_key, multipart_id, not_before)
VALUES (?1, ?2, ?3)
`

type InsertDeletionParams struct {
	ObjectKey   string
	MultipartID sql.NullString
	NotBefore   int64
}

func (q *Queries) InsertDeletion(ctx context.Context, arg InsertDeletionParams) error {
	_, err := q.db.ExecContext(ctx, insertDeletion, arg.ObjectKey, arg.MultipartID, arg.NotBefore)
	return err
}

const insertUpload = `-- name: InsertUpload :exec
INSERT INTO uploads (
    id, name, root, parent_id, uploader, data_key, index_key, links_key,
    multipart_id, data_size, objects, state, issued_at, deadline
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13, ?14
)
`

type InsertUploadParams struct {
	ID          string
	Name        string
	Root        []byte
	ParentID    sql.NullInt64
	Uploader    string
	DataKey     string
	IndexKey    string
	LinksKey    string
	MultipartID sql.NullString
	DataSize    int64
	Objects     int64
	State       string
	IssuedAt    int64
	Deadline    int64
}

func (q *Queries) InsertUpload(ctx context.Context, arg InsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, insertUpload,
		arg.ID,
		arg.Name,
		arg.Root,
		arg.ParentID,
		arg.Uploader,
		arg.DataKey,
		arg.IndexKey,
		arg.LinksKey,
		arg.MultipartID,
		arg.DataSize,
		arg.Objects,
		arg.State,
		arg.IssuedAt,
		arg.Deadline,
	)
	return err
}

const listUploads = `-- name: ListUploads :many
SELECT id, name, root, parent_id, uploader, data_key, index_key, links_key, multipart_id, data_size, objects, state, issued_at, deadline FROM uploads ORDER BY issued_at, id
`

func (q *Queries) ListUploads(ctx context.Context) ([]Upload, error) {
	rows, err := q.db.QueryContext(ctx, listUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Root,
			&i.ParentID,
			&i.Uploader,
			&i.DataKey,
			&i.IndexKey,
			&i.LinksKey,
			&i.MultipartID,
			&i.DataSize,
			&i.Objects,
			&i.State,
			&i.IssuedAt,
			&i.Deadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetVerifying = `-- name: ResetVerifying :exec
UPDATE uploads SET state = 'pending' WHERE state = 'verifying'
`

func (q *Queries) ResetVerifying(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetVerifying)
	return err
}

const setUploadState = `-- name: SetUploadState :execrows
UPDATE uploads SET state = ?1 WHERE id = ?2
`

type SetUploadStateParams struct {
	State string
	ID    string
}

func (q *Queries) SetUploadState(ctx context.Context, arg SetUploadStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUploadState, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const uploadByID = `-- name: UploadByID :one
SELECT id, name, root, parent_id, uploader, data_key, index_key, links_key, multipart_id, data_size, objects, state, issued_at, deadline FROM uploads WHERE id = ?1
`

func (q *Queries) UploadByID(ctx context.Context, id string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, uploadByID, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Root,
		&i.ParentID,
		&i.Uploader,
		&i.DataKey,
		&i.IndexKey,
		&i.LinksKey,
		&i.MultipartID,
		&i.DataSize,
		&i.Objects,
		&i.State,
		&i.IssuedAt,
		&i.Deadline,
	)
	return i, err
}
